apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ivanchenko-io-wildcard
spec:
  secretName: ivanchenko-io-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: ivanchenko.io
  dnsNames:
    - ivanchenko.io
    - "*.ivanchenko.io"
