apiVersion: v2
name: grafana
version: 0.0.0
dependencies:
  - name: grafana-operator
    version: 5.21.4
    repository: https://grafana.github.io/helm-charts
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
