apiVersion: v2
name: core-keeper
version: 0.0.0
dependencies:
  - name: app-template
    version: 4.6.0
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: core-keeper
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
