apiVersion: v2
name: backrest
version: 0.0.0
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: backrest
  - name: backrest-volsync-operator
    version: 0.3.1
    repository: oci://ghcr.io/vanchaxy/backrest-volsync-operator-chart
