apiVersion: v2
name: kube-prometheus-stack
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 80.13.3
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.49.0
  - name: fluent-bit
    repository: https://grafana.github.io/helm-charts
    version: 2.6.0
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
