apiVersion: v2
name: telemetry
version: 0.0.0
dependencies:
  - name: victoria-metrics-k8s-stack
    version: 0.70.0
    repository: https://victoriametrics.github.io/helm-charts/
  - name: prometheus-operator-crds
    version: 27.0.0
    repository: https://prometheus-community.github.io/helm-charts/
