apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ip-pool
spec:
  blocks:
    - start: 192.168.50.230
      stop: 192.168.50.250
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: public-pool
spec:
  serviceSelector:
    matchLabels:
      expose-public: "true"
  blocks:
    - cidr: "46.38.230.69/32"
