apiVersion: v2
name: abiotic-factor
version: 0.0.0
dependencies:
  - name: app-template
    version: 4.5.0
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: abiotic-factor
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
