apiVersion: v2
name: pocket-id
version: 0.0.0
dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: pocket-id
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
