apiVersion: v2
name: immich
version: 0.0.0
dependencies:
  - name: immich
    repository: https://immich-app.github.io/immich-charts
    version: 0.10.3
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.26.1
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
