apiVersion: v2
name: argocd
version: 0.0.0
dependencies:
  - name: argo-cd
    version: 9.3.0
    repository: https://argoproj.github.io/argo-helm
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
  - name: argocd-apps
    version: 2.0.4
    repository: https://argoproj.github.io/argo-helm
