apiVersion: v2
name: longhorn
version: 0.0.0
dependencies:
  - name: longhorn
    version: 1.11.0
    repository: https://charts.longhorn.io
  - name: helpers
    version: 0.1.0
    repository: file://../../../k8s/_helpers
