apiVersion: frp.zufardhiyaulhaq.com/v1alpha1
kind: Upstream
metadata:
  name: abiotic-factor
spec:
  client: frp-client
  udp:
    host: abiotic-factor.abiotic-factor.svc.cluster.local
    port: 7777
    server:
      port: 7777
