apiVersion: operator.victoriametrics.com/v1
kind: "VLAgent"
metadata:
  name: victoria-logs-agent
spec:
  k8sCollector:
    enabled: true
  remoteWrite:
    - url: "http://vlsingle-victoria-logs:9428/internal/insert"
